// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srhiynsecewnhksiyqar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyaGl5bnNlY2V3bmhrc2l5cWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODk0NDYsImV4cCI6MjA2NTE2NTQ0Nn0.kSR0IbgYwNobGYznNNM4VY4UAfECFMenVEJvGW7tGRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);